// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2Kf-G7z5LOXU2vBUkAAhfEdEQ2k6lh6A',
    appId: '1:248858408657:web:5f22a3ad1fec2ba7eab7f0',
    messagingSenderId: '248858408657',
    projectId: 'chatapp-a0e8a',
    authDomain: 'chatapp-a0e8a.firebaseapp.com',
    storageBucket: 'chatapp-a0e8a.firebasestorage.app',
    measurementId: 'G-LMW60J2PQN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIsBYI_HLBvVXk32m7jKP8qFeWS6ZUErw',
    appId: '1:248858408657:android:93fd1106610a7330eab7f0',
    messagingSenderId: '248858408657',
    projectId: 'chatapp-a0e8a',
    storageBucket: 'chatapp-a0e8a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFB9Q4UId3Tv9uwiTg1fjgsGH2n06zCBU',
    appId: '1:248858408657:ios:23fde5968c4a8c5ceab7f0',
    messagingSenderId: '248858408657',
    projectId: 'chatapp-a0e8a',
    storageBucket: 'chatapp-a0e8a.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFB9Q4UId3Tv9uwiTg1fjgsGH2n06zCBU',
    appId: '1:248858408657:ios:23fde5968c4a8c5ceab7f0',
    messagingSenderId: '248858408657',
    projectId: 'chatapp-a0e8a',
    storageBucket: 'chatapp-a0e8a.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2Kf-G7z5LOXU2vBUkAAhfEdEQ2k6lh6A',
    appId: '1:248858408657:web:a47f6132171a450ceab7f0',
    messagingSenderId: '248858408657',
    projectId: 'chatapp-a0e8a',
    authDomain: 'chatapp-a0e8a.firebaseapp.com',
    storageBucket: 'chatapp-a0e8a.firebasestorage.app',
    measurementId: 'G-N2MR0S4S1B',
  );

}